import "./global.css"
import React from 'react'
import Navbar from './components/navbar'
import { Footer } from './components/footer'
import {aboutMeData, pages, contactMeLinks} from './data/data'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head />
      <body>
        {/* <Navbar name={aboutMeData.name} pages={pages} contactMeLinks={contactMeLinks} /> */}
        <Navbar />
        {children}
      </body>
    </html>
  );
}
